"""o formulario do Marketing vira linhas (Spec 043, fatia A)

Revision ID: 0017_formulario_do_marketing
Revises: 0016_formulario_de_solicitacao
Create Date: 2026-08-24

A 0016 criou a estrutura; esta poe DADO nela: o formulario que hoje mora em
`web/lib/solicitacaoForm.ts` vira 1 formulario + 11 secoes + 108 perguntas, no
time de Marketing.

⚠️ DUAS REGRAS PARA ACHAR O TIME (ajustado em 24/08, depois de olhar os dois
bancos): primeiro o id de producao; se ele nao existir ali, o time RAIZ de cada
workspace. A segunda nasceu de um achado -- em DEV o id de producao nao existe,
a migration saiu em silencio, e a fatia B ficaria sem formulario nenhum para
testar. Em dev o Marketing E a raiz (`parent_team_id IS NULL`), com sete
subtimes pendurados; a raiz e estrutural, o nome nao.

⚠️⚠️ E ELA CONTINUA NO-OP QUANDO NAO HA TIME NENHUM, que e a protecao que
importa: o BANCO DE TESTE roda `alembic upgrade head` num banco VAZIO, sem
workspace e sem time. Uma migration de dados que assuma a existencia de uma linha
especifica quebra toda a suite -- e quebraria DEPOIS de eu ter entregue, que e
como as duas falhas anteriores desta fatia chegaram na Camila.

⚠️ E ELA E IDEMPOTENTE: se o formulario com este slug ja existe, sai sem fazer
nada. Migration de dados que roda duas vezes em ambiente de homologacao e
situacao normal, nao acidente.

⚠️ OS DADOS NAO FORAM TRANSCRITOS A MAO. Eles sairam do PROPRIO
`solicitacaoForm.ts`, lido pelo parser de TypeScript do projeto (um teste
temporario que serializou `CATEGORIAS` em JSON). Transcrever 108 perguntas a
mao seria garantir que uma delas sairia diferente -- e a diferenca so
apareceria para quem preenchesse o formulario.

⚠️ E O FORMULARIO NASCE PUBLICADO. Ele e a porta que ja esta no ar hoje; nascer
em rascunho faria a fatia B precisar de um gesto manual em producao para
religar o que nunca esteve desligado.

⚠️ AS SOLICITACOES ANTIGAS SAO LIGADAS A ELE pelo slug da categoria. As que
tiverem categoria fora das 11 (nao ha nenhuma hoje, mas o campo e texto)
continuam com `form_id` NULL -- e continuam na fila, porque o `JOIN` e `LEFT`.
"""

import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0017_formulario_do_marketing"
down_revision: str | None = "0016_formulario_de_solicitacao"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: O time de Marketing em PRODUCAO, informado pela Camila em 22/08.
#:
#: ⚠️ CRAVADO, e nao resolvido por nome: "Marketing" e texto que alguem
#: renomeia, o id nao muda.
TEAM_MARKETING = "b8387155-9688-4e58-b596-8d46906a68dd"

SLUG_DO_FORMULARIO = "marketing"
TITULO_DO_FORMULARIO = "Solicitação ao Marketing"

#: Extraido de `web/lib/solicitacaoForm.ts` -- ver o aviso do topo.
#: `ref` e `show_if_ref` sao os ids do TypeScript; eles so existem para
#: amarrar a condicional dentro desta migration, e nao vao para o banco.
SECOES = [{'slug': 'arte',
  'title': 'Criar uma arte',
  'emoji': '🖼️',
  'sla_text': 'Até 5 dias úteis',
  'summary_ref': 'uso',
  'position': 0,
  'questions': [{'ref': 'formato',
                 'label': 'Formato da arte',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Digital', 'Impresso'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'tipo_arte',
                 'label': 'O que você precisa?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Banner',
                             'Post para redes sociais',
                             'Cartaz',
                             'Folder/Flyer',
                             'Apresentação',
                             'Arte para TV interna',
                             'Layout para polo',
                             'Outro'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 1},
                {'ref': 'medidas_polo',
                 'label': 'Medidas e foto do local de aplicação (link)',
                 'kind': 'link',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': 'Para fachada de polo ou ambientação interna é OBRIGATÓRIO '
                         'informar as medidas e foto de onde a arte será aplicada. '
                         'Suba os arquivos no Drive e cole o link com acesso liberado.',
                 'show_if_ref': 'tipo_arte',
                 'show_if_value': 'Layout para polo',
                 'position': 2},
                {'ref': 'uso',
                 'label': 'Para que essa arte será utilizada?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 3},
                {'ref': 'campanha',
                 'label': 'Este material faz parte de uma campanha ou projeto?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 4},
                {'ref': 'campanha_qual',
                 'label': 'Qual campanha ou projeto?',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'campanha',
                 'show_if_value': 'Sim',
                 'position': 5},
                {'ref': 'conteudo_pronto',
                 'label': 'O conteúdo já está pronto?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 6},
                {'ref': 'referencia',
                 'label': 'Referência (link do Drive)',
                 'kind': 'link',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': 'Tem alguma referência visual? Suba no Google Drive e cole '
                         'aqui o link com acesso liberado.',
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 7},
                {'ref': 'objetivo',
                 'label': 'Qual o objetivo desta solicitação?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Divulgar',
                             'Informar',
                             'Atrair novos alunos',
                             'Engajar alunos',
                             'Apoiar um evento',
                             'Outro'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 8},
                {'ref': 'obs',
                 'label': 'Observações',
                 'kind': 'textoLongo',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 9}]},
 {'slug': 'foto',
  'title': 'Sessão ou edição de fotos',
  'emoji': '📸',
  'sla_text': 'Sessão: 5 a 15 dias úteis · Edição: 3 a 7 dias úteis',
  'summary_ref': 'foto_objetivo',
  'position': 1,
  'questions': [{'ref': 'foto_tipo',
                 'label': 'O que você precisa?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sessão de fotos',
                             'Edição de fotos (cor / luz / finalização)'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'foto_objetivo',
                 'label': 'Qual o objetivo da sessão de fotos?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Sessão de fotos',
                 'position': 1},
                {'ref': 'foto_formato',
                 'label': 'Qual formato?',
                 'kind': 'escolha',
                 'required': False,
                 'options': ['Horizontal', 'Vertical', 'Quadrado'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Sessão de fotos',
                 'position': 2},
                {'ref': 'foto_ref_estilo',
                 'label': 'Tem referência de sessão produzida anteriormente? (retrato, '
                          'evento, produto, artístico, corporativo…)',
                 'kind': 'texto',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Sessão de fotos',
                 'position': 3},
                {'ref': 'foto_participantes',
                 'label': 'Quem participará das fotos?',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Sessão de fotos',
                 'position': 4},
                {'ref': 'foto_local',
                 'label': 'Local das fotos',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Sessão de fotos',
                 'position': 5},
                {'ref': 'foto_roteiro',
                 'label': 'Existe roteiro ou direcional criativo?',
                 'kind': 'escolha',
                 'required': False,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Sessão de fotos',
                 'position': 6},
                {'ref': 'foto_data_flag',
                 'label': 'Existe alguma data que precisa ser considerada? (evento, '
                          'lançamento, início de campanha)',
                 'kind': 'escolha',
                 'required': False,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Sessão de fotos',
                 'position': 7},
                {'ref': 'foto_data',
                 'label': 'Qual é essa data?',
                 'kind': 'data',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_data_flag',
                 'show_if_value': 'Sim',
                 'position': 8},
                {'ref': 'foto_refs',
                 'label': 'Outras referências (link do Drive)',
                 'kind': 'link',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Sessão de fotos',
                 'position': 9},
                {'ref': 'fotoed_tiradas',
                 'label': 'As fotos já foram tiradas?',
                 'kind': 'escolha',
                 'required': False,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Edição de fotos (cor / luz / finalização)',
                 'position': 10},
                {'ref': 'fotoed_arquivos',
                 'label': 'Arquivos e informações para edição (link do Drive)',
                 'kind': 'link',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': 'O prazo de edição só começa a contar após o recebimento de '
                         'TODO o material.',
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Edição de fotos (cor / luz / finalização)',
                 'position': 11},
                {'ref': 'fotoed_oque',
                 'label': 'O que precisa ser editado?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Edição de fotos (cor / luz / finalização)',
                 'position': 12},
                {'ref': 'fotoed_data_flag',
                 'label': 'Existe alguma data que precisa ser considerada?',
                 'kind': 'escolha',
                 'required': False,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Edição de fotos (cor / luz / finalização)',
                 'position': 13},
                {'ref': 'fotoed_data',
                 'label': 'Qual é essa data?',
                 'kind': 'data',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'fotoed_data_flag',
                 'show_if_value': 'Sim',
                 'position': 14},
                {'ref': 'fotoed_refs',
                 'label': 'Referências (link, opcional)',
                 'kind': 'link',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'foto_tipo',
                 'show_if_value': 'Edição de fotos (cor / luz / finalização)',
                 'position': 15}]},
 {'slug': 'video',
  'title': 'Gravar ou editar um vídeo',
  'emoji': '🎥',
  'sla_text': 'Gravação + edição: 7 a 15 dias úteis · Só edição: 3 a 7 dias úteis',
  'summary_ref': 'video_objetivo',
  'position': 2,
  'questions': [{'ref': 'video_tipo',
                 'label': 'O que você precisa?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Gravar e editar um vídeo',
                             'Apenas editar um vídeo já existente'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'video_objetivo',
                 'label': 'Qual o objetivo do vídeo?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'video_tipo',
                 'show_if_value': 'Gravar e editar um vídeo',
                 'position': 1},
                {'ref': 'video_formato',
                 'label': 'Qual formato?',
                 'kind': 'escolha',
                 'required': False,
                 'options': ['Horizontal', 'Vertical', 'Quadrado'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'video_tipo',
                 'show_if_value': 'Gravar e editar um vídeo',
                 'position': 2},
                {'ref': 'video_ref_estilo',
                 'label': 'Tem referência de vídeo produzido anteriormente? '
                          '(lançamento, cobertura de evento, institucional…)',
                 'kind': 'texto',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'video_tipo',
                 'show_if_value': 'Gravar e editar um vídeo',
                 'position': 3},
                {'ref': 'video_participantes',
                 'label': 'Quem participará da gravação?',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'video_tipo',
                 'show_if_value': 'Gravar e editar um vídeo',
                 'position': 4},
                {'ref': 'video_local',
                 'label': 'Local da gravação',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'video_tipo',
                 'show_if_value': 'Gravar e editar um vídeo',
                 'position': 5},
                {'ref': 'video_roteiro',
                 'label': 'Existe roteiro?',
                 'kind': 'escolha',
                 'required': False,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'video_tipo',
                 'show_if_value': 'Gravar e editar um vídeo',
                 'position': 6},
                {'ref': 'videoed_gravado',
                 'label': 'O vídeo já foi gravado?',
                 'kind': 'escolha',
                 'required': False,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'video_tipo',
                 'show_if_value': 'Apenas editar um vídeo já existente',
                 'position': 7},
                {'ref': 'videoed_arquivos',
                 'label': 'Arquivos e informações que aparecerão em tela (link do '
                          'Drive)',
                 'kind': 'link',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': 'O prazo de edição só começa a contar após o recebimento de '
                         'TODO o material.',
                 'show_if_ref': 'video_tipo',
                 'show_if_value': 'Apenas editar um vídeo já existente',
                 'position': 8},
                {'ref': 'videoed_oque',
                 'label': 'O que precisa ser editado?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'video_tipo',
                 'show_if_value': 'Apenas editar um vídeo já existente',
                 'position': 9},
                {'ref': 'videoed_roteiro',
                 'label': 'Existe roteiro?',
                 'kind': 'escolha',
                 'required': False,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'video_tipo',
                 'show_if_value': 'Apenas editar um vídeo já existente',
                 'position': 10},
                {'ref': 'video_data_flag',
                 'label': 'Existe alguma data em que o vídeo precisa estar disponível? '
                          '(evento, lançamento, início de campanha)',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 11},
                {'ref': 'video_data',
                 'label': 'Qual é essa data?',
                 'kind': 'data',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'video_data_flag',
                 'show_if_value': 'Sim',
                 'position': 12},
                {'ref': 'video_onde',
                 'label': 'O vídeo será utilizado onde?',
                 'kind': 'multi',
                 'required': False,
                 'options': ['Instagram',
                             'TikTok',
                             'YouTube',
                             'Site',
                             'TV interna',
                             'Evento',
                             'Outro'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 13},
                {'ref': 'video_refs',
                 'label': 'Outras referências (link, opcional)',
                 'kind': 'link',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 14}]},
 {'slug': 'divulgacao',
  'title': 'Divulgar uma ação, campanha ou comunicado',
  'emoji': '📣',
  'sla_text': 'Solicitar com no mínimo 10 dias úteis de antecedência',
  'summary_ref': 'div_nome',
  'position': 3,
  'questions': [{'ref': 'div_nome',
                 'label': 'Nome da ação',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'div_desc',
                 'label': 'Descreva resumidamente o que será divulgado',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 1},
                {'ref': 'div_tipo',
                 'label': 'Qual é o tipo da ação?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Evento de grande porte',
                             'Evento de pequeno e médio porte',
                             'Lançamento de curso',
                             'Live',
                             'Campanha',
                             'Processo Seletivo',
                             'Comunicado',
                             'Projeto',
                             'Parceria',
                             'Mutirão de oportunidades',
                             'Outro'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 2},
                {'ref': 'div_objetivo',
                 'label': 'Qual é o principal objetivo desta comunicação?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Informar',
                             'Gerar inscrições',
                             'Divulgar um lançamento',
                             'Engajar a comunidade',
                             'Fortalecer a marca',
                             'Divulgar um resultado',
                             'Captar lead',
                             'Outro'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 3},
                {'ref': 'div_publico',
                 'label': 'Quem precisa receber essa informação?',
                 'kind': 'multi',
                 'required': True,
                 'options': ['Alunos atuais',
                             'Candidatos (Leads)',
                             'Professores',
                             'Colaboradores',
                             'Polos',
                             'Empresas parceiras',
                             'Influenciadores',
                             'Público externo',
                             'Outro'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 4},
                {'ref': 'div_publico_pq',
                 'label': 'Por que este é o público prioritário?',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 5},
                {'ref': 'div_inicio',
                 'label': 'Quando a comunicação precisa começar?',
                 'kind': 'data',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 6},
                {'ref': 'div_limite',
                 'label': 'Existe uma data limite ou evento principal? Qual data?',
                 'kind': 'data',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 7},
                {'ref': 'div_material_pronto',
                 'label': 'Já existe algum material pronto (story, vídeo, banner)?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 8},
                {'ref': 'div_producao',
                 'label': 'O Marketing precisa produzir algum material?',
                 'kind': 'multi',
                 'required': False,
                 'options': ['Artes',
                             'Vídeo',
                             'Texto',
                             'Roteiro',
                             'Cobertura',
                             'Fotografia',
                             'Outro'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 9},
                {'ref': 'div_obs',
                 'label': 'Observações',
                 'kind': 'textoLongo',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 10}]},
 {'slug': 'evento',
  'title': 'Organizar um evento',
  'emoji': '📅',
  'sla_text': 'Prazo em definição pelo time de marketing',
  'summary_ref': 'ev_nome',
  'position': 4,
  'questions': [{'ref': 'ev_nome',
                 'label': 'Nome do evento',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'ev_briefing',
                 'label': 'O evento já possui briefing ou planejamento?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 1},
                {'ref': 'ev_briefing_link',
                 'label': 'Link do briefing/planejamento (Drive)',
                 'kind': 'link',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'ev_briefing',
                 'show_if_value': 'Sim',
                 'position': 2},
                {'ref': 'ev_confirmado',
                 'label': 'O evento já está confirmado?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 3},
                {'ref': 'ev_tipo',
                 'label': 'Tipo',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Presencial', 'Online', 'Híbrido'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 4},
                {'ref': 'ev_data',
                 'label': 'Data',
                 'kind': 'data',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 5},
                {'ref': 'ev_hora',
                 'label': 'Horário',
                 'kind': 'texto',
                 'required': False,
                 'options': [],
                 'placeholder': 'ex.: 19:00',
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 6},
                {'ref': 'ev_local',
                 'label': 'Local',
                 'kind': 'texto',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 7},
                {'ref': 'ev_publico',
                 'label': 'Público esperado',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Até 50 pessoas',
                             '50 a 150 pessoas',
                             '150 a 300 pessoas',
                             'Mais de 300 pessoas'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 8},
                {'ref': 'ev_objetivo',
                 'label': 'Qual é o objetivo do evento?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Captação',
                             'Relacionamento',
                             'Institucional',
                             'Acadêmico',
                             'Outro'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 9},
                {'ref': 'ev_divulgacao',
                 'label': 'O evento precisa de divulgação?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 10},
                {'ref': 'ev_div_inicio',
                 'label': 'Existe alguma data em que a divulgação precisa começar?',
                 'kind': 'data',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'ev_divulgacao',
                 'show_if_value': 'Sim',
                 'position': 11},
                {'ref': 'ev_cobertura',
                 'label': 'Precisa de cobertura de foto ou vídeo?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 12},
                {'ref': 'ev_parceiros',
                 'label': 'O evento possui parceiros?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 13},
                {'ref': 'ev_parceiros_quais',
                 'label': 'Quais parceiros?',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'ev_parceiros',
                 'show_if_value': 'Sim',
                 'position': 14},
                {'ref': 'ev_anexos',
                 'label': 'Anexos (link do Drive)',
                 'kind': 'link',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 15},
                {'ref': 'ev_obs',
                 'label': 'Observações',
                 'kind': 'textoLongo',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 16}]},
 {'slug': 'site',
  'title': 'Criar ou atualizar uma página no site',
  'emoji': '🌐',
  'sla_text': 'Até 3 dias úteis após a solicitação completa e aprovada',
  'summary_ref': 'site_oque',
  'position': 5,
  'questions': [{'ref': 'site_tipo',
                 'label': 'O que você precisa?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Criar uma nova página',
                             'Atualizar uma página existente',
                             'Criar uma Landing Page (LP)',
                             'Não tenho certeza'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'site_objetivo',
                 'label': 'Qual é o objetivo dessa página?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Divulgar um curso',
                             'Divulgar um evento',
                             'Captar leads',
                             'Disponibilizar informações',
                             'Outro'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 1},
                {'ref': 'site_link',
                 'label': 'Link da página existente',
                 'kind': 'link',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'site_tipo',
                 'show_if_value': 'Atualizar uma página existente',
                 'position': 2},
                {'ref': 'site_oque',
                 'label': 'O que precisa ser criado ou alterado?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 3},
                {'ref': 'site_texto_pronto',
                 'label': 'O conteúdo (texto) já está pronto?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 4},
                {'ref': 'site_imagens',
                 'label': 'As imagens já estão disponíveis?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 5},
                {'ref': 'site_form',
                 'label': 'A página precisa de formulário para captação de '
                          'interessados?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não', 'Não sei'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 6},
                {'ref': 'site_data',
                 'label': 'Existe alguma data importante para publicação?',
                 'kind': 'data',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 7},
                {'ref': 'site_anexos',
                 'label': 'Anexos (link do Drive)',
                 'kind': 'link',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 8},
                {'ref': 'site_obs',
                 'label': 'Observações',
                 'kind': 'textoLongo',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 9}]},
 {'slug': 'email',
  'title': 'Enviar comunicação por e-mail ou WhatsApp',
  'emoji': '📧',
  'sla_text': 'Solicitar com no mínimo 2 dias úteis de antecedência',
  'summary_ref': 'em_oque',
  'position': 6,
  'questions': [{'ref': 'em_oque',
                 'label': 'O que deseja comunicar?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'em_paraquem',
                 'label': 'Para quem?',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 1},
                {'ref': 'em_data',
                 'label': 'Existe uma data limite para envio?',
                 'kind': 'data',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 2},
                {'ref': 'em_texto_pronto',
                 'label': 'O texto já está pronto?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 3},
                {'ref': 'em_lista',
                 'label': 'Existe lista de destinatários?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 4},
                {'ref': 'em_obs',
                 'label': 'Observações',
                 'kind': 'textoLongo',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 5}]},
 {'slug': 'lancamento',
  'title': 'Lançar um curso, campanha ou projeto',
  'emoji': '🚀',
  'sla_text': 'Até 15 dias úteis após a solicitação completa e aprovada',
  'summary_ref': 'lan_oque',
  'position': 7,
  'questions': [{'ref': 'lan_oque',
                 'label': 'O que será lançado?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'lan_data',
                 'label': 'Existe uma data prevista? Qual?',
                 'kind': 'data',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 1},
                {'ref': 'lan_briefing',
                 'label': 'Já existe planejamento / briefing?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 2},
                {'ref': 'lan_briefing_link',
                 'label': 'Link do briefing (Drive)',
                 'kind': 'link',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'lan_briefing',
                 'show_if_value': 'Sim',
                 'position': 3},
                {'ref': 'lan_obs',
                 'label': 'Observações',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 4}]},
 {'slug': 'revisao',
  'title': 'Revisar ou atualizar um material existente',
  'emoji': '✏️',
  'sla_text': 'Prazo em definição pelo time de marketing',
  'summary_ref': 'rev_oque',
  'position': 8,
  'questions': [{'ref': 'rev_oque',
                 'label': 'O que deseja alterar?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'rev_material',
                 'label': 'Material que precisa ser revisado (link do Drive)',
                 'kind': 'link',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 1},
                {'ref': 'rev_detalhe',
                 'label': 'O que precisa ser alterado (detalhe)?',
                 'kind': 'textoLongo',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 2},
                {'ref': 'rev_data',
                 'label': 'Existe alguma data que obrigatoriamente precisa ser '
                          'considerada?',
                 'kind': 'data',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 3},
                {'ref': 'rev_obs',
                 'label': 'Observações',
                 'kind': 'textoLongo',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 4}]},
 {'slug': 'impressao',
  'title': 'Solicitar impressão de um material',
  'emoji': '📦',
  'sla_text': 'Prazo em definição pelo time de marketing',
  'summary_ref': 'imp_oque',
  'position': 9,
  'questions': [{'ref': 'imp_aviso',
                 'label': 'Atenção: impressão é atendida SOMENTE na sede.',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Estou ciente'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'imp_oque',
                 'label': 'O que será impresso?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 1},
                {'ref': 'imp_finalizado',
                 'label': 'O arquivo está finalizado?',
                 'kind': 'escolha',
                 'required': True,
                 'options': ['Sim', 'Não'],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 2},
                {'ref': 'imp_arquivo',
                 'label': 'Arquivo para impressão (link do Drive)',
                 'kind': 'link',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': 'imp_finalizado',
                 'show_if_value': 'Sim',
                 'position': 3},
                {'ref': 'imp_qtd',
                 'label': 'Quantidade',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 4},
                {'ref': 'imp_tamanho',
                 'label': 'Tamanho',
                 'kind': 'texto',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 5},
                {'ref': 'imp_data',
                 'label': 'Existe alguma data que obrigatoriamente precisa ser '
                          'considerada?',
                 'kind': 'data',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 6},
                {'ref': 'imp_obs',
                 'label': 'Observações',
                 'kind': 'textoLongo',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 7}]},
 {'slug': 'outro',
  'title': 'Outro assunto',
  'emoji': '❓',
  'sla_text': None,
  'summary_ref': 'out_desc',
  'position': 10,
  'questions': [{'ref': 'out_desc',
                 'label': 'Descreva sua solicitação',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 0},
                {'ref': 'out_objetivo',
                 'label': 'Qual o objetivo da solicitação?',
                 'kind': 'textoLongo',
                 'required': True,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 1},
                {'ref': 'out_data',
                 'label': 'Existe alguma data que obrigatoriamente precisa ser '
                          'considerada?',
                 'kind': 'data',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 2},
                {'ref': 'out_anexos',
                 'label': 'Anexos (link do Drive)',
                 'kind': 'link',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 3},
                {'ref': 'out_obs',
                 'label': 'Observações',
                 'kind': 'textoLongo',
                 'required': False,
                 'options': [],
                 'placeholder': None,
                 'help': None,
                 'show_if_ref': None,
                 'show_if_value': None,
                 'position': 4}]}]


def upgrade() -> None:
    conn = op.get_bind()

    # ⚠️⚠️ DUAS REGRAS PARA ACHAR O TIME, E A SEGUNDA NASCEU DE UM ACHADO NO
    # BANCO (24/08). A primeira versao so tinha o id cravado, e em DEV ela saiu
    # em silencio -- o id de producao nao existe la. Consequencia que so
    # apareceu quando a Camila rodou a consulta: **a fatia B ficaria sem
    # formulario nenhum para testar em dev**, e o defeito seria descoberto em
    # producao.
    #
    # A regra 2 e "o time RAIZ de cada workspace", e ela e ESTRUTURAL. Foi
    # escolhida depois de olhar os dois bancos: em dev o Marketing E a raiz
    # (`d03c9ede-...`, `parent_team_id IS NULL`), com sete subtimes pendurados.
    # Cair no nome ("Marketing") seria depender de texto que alguem renomeia;
    # cair na raiz depende da forma da arvore, que ninguem muda sem querer.
    #
    # ⚠️ E O BANCO DE TESTE CONTINUA NO-OP: vazio, ele nao tem workspace nem
    # time raiz, entao as duas regras devolvem nada. Era essa a protecao da
    # primeira versao, e ela nao se perdeu.
    alvos = conn.execute(
        # ⚠️ `CAST(... AS uuid)` porque `TEAM_MARKETING` e uma STRING Python
        # indo para uma coluna `uuid`. Sem o cast, o asyncpg recusa o bind -- e
        # recusaria na SUA maquina, nao na minha, que e como as duas falhas
        # anteriores desta fatia chegaram ate voce.
        sa.text("SELECT id, workspace_id FROM team WHERE id = CAST(:t AS uuid)"),
        {"t": TEAM_MARKETING},
    ).all()
    if not alvos:
        alvos = conn.execute(
            sa.text(
                "SELECT id, workspace_id FROM team WHERE parent_team_id IS NULL"
            )
        ).all()
    for alvo in alvos:
        _semear(conn, team_id=alvo.id, workspace_id=alvo.workspace_id)


def _semear(conn, *, team_id, workspace_id) -> None:
    """Cria o formulario num time, se ele ainda nao existir ali.

    ⚠️ IDEMPOTENTE POR SLUG. Migration de dados rodando duas vezes em
    homologacao e situacao normal, nao acidente.
    """
    ja_existe = conn.execute(
        sa.text(
            "SELECT 1 FROM solicitation_form "
            "WHERE workspace_id = :w AND slug = :s AND deleted_at IS NULL"
        ),
        {"w": workspace_id, "s": SLUG_DO_FORMULARIO},
    ).first()
    if ja_existe is not None:
        return

    form_id = conn.execute(
        sa.text(
            "INSERT INTO solicitation_form "
            "(workspace_id, team_id, slug, title, description, is_published) "
            "VALUES (:w, :t, :s, :ti, '', true) RETURNING id"
        ),
        {
            "w": workspace_id,
            "t": team_id,
            "s": SLUG_DO_FORMULARIO,
            "ti": TITULO_DO_FORMULARIO,
        },
    ).scalar_one()

    for secao in SECOES:
        section_id = conn.execute(
            sa.text(
                "INSERT INTO solicitation_section "
                "(workspace_id, form_id, slug, title, emoji, sla_text, position) "
                "VALUES (:w, :f, :s, :t, :e, :sla, :p) RETURNING id"
            ),
            {
                "w": workspace_id,
                "f": form_id,
                "s": secao["slug"],
                "t": secao["title"],
                "e": secao["emoji"],
                "sla": secao["sla_text"],
                "p": secao["position"],
            },
        ).scalar_one()

        # ⚠️ DUAS PASSADAS, E A ORDEM E OBRIGATORIA. A condicional aponta para
        # OUTRA pergunta, e o id dela so existe depois do INSERT. Numa passada
        # so, `show_if_question_id` ficaria sempre NULL -- e o formulario
        # publico mostraria os 34 campos condicionais SEMPRE, o que ninguem
        # olhando o banco perceberia.
        ids_por_ref: dict[str, str] = {}
        for q in secao["questions"]:
            qid = conn.execute(
                sa.text(
                    "INSERT INTO solicitation_question "
                    "(workspace_id, section_id, label, kind, required, options, "
                    " placeholder, help, position) "
                    "VALUES (:w, :s, :l, :k, :r, CAST(:o AS jsonb), :ph, :h, :p) "
                    "RETURNING id"
                ),
                {
                    "w": workspace_id,
                    "s": section_id,
                    "l": q["label"],
                    "k": q["kind"],
                    "r": q["required"],
                    "o": json.dumps(q["options"], ensure_ascii=False),
                    "ph": q["placeholder"],
                    "h": q["help"],
                    "p": q["position"],
                },
            ).scalar_one()
            ids_por_ref[q["ref"]] = qid

        for q in secao["questions"]:
            if q["show_if_ref"] is None:
                continue
            alvo = ids_por_ref.get(q["show_if_ref"])
            if alvo is None:
                # ⚠️ Condicional apontando para pergunta de OUTRA secao nao
                # existe no formulario de hoje. Se um dia existir, ela fica sem
                # condicao (campo sempre visivel) em vez de estourar a
                # migration -- visivel demais e recuperavel, migration
                # quebrada no meio nao.
                continue
            conn.execute(
                sa.text(
                    "UPDATE solicitation_question "
                    "SET show_if_question_id = :alvo, show_if_value = :v "
                    "WHERE id = :id"
                ),
                {"alvo": alvo, "v": q["show_if_value"], "id": ids_por_ref[q["ref"]]},
            )

        if secao["summary_ref"] and secao["summary_ref"] in ids_por_ref:
            conn.execute(
                sa.text(
                    "UPDATE solicitation_section SET summary_question_id = :q "
                    "WHERE id = :s"
                ),
                {"q": ids_por_ref[secao["summary_ref"]], "s": section_id},
            )

    # ⚠️ SO AS QUE AINDA NAO TEM FORMULARIO, e so as categorias que existem
    # neste formulario. `category` e texto livre no banco; uma linha com
    # categoria desconhecida fica sem vinculo, e continua na fila pelo LEFT JOIN.
    conn.execute(
        sa.text(
            "UPDATE solicitation SET form_id = :f "
            "WHERE workspace_id = :w AND form_id IS NULL AND category IN "
            "(SELECT slug FROM solicitation_section WHERE form_id = :f)"
        ),
        {"f": form_id, "w": workspace_id},
    )


def downgrade() -> None:
    """Desfaz a semeadura em QUALQUER workspace, e nao so no time cravado.

    ⚠️ ELE PRECISA ESPELHAR AS DUAS REGRAS DO `upgrade`. A primeira versao
    procurava so o time de producao -- entao, num banco que caiu no fallback da
    raiz, o downgrade sairia em silencio deixando o formulario para tras, e o
    upgrade seguinte o encontraria "ja existente" e nao o recriaria. Migration
    que nao desfaz o que fez e pior que migration sem downgrade.

    ⚠️ O VINCULO DAS SOLICITACOES E DESFEITO ANTES do DELETE. As secoes e
    perguntas somem por CASCADE, mas `solicitation.form_id` NAO tem FK (ver a
    0016) -- sem este UPDATE, elas ficariam apontando para um id que nao existe
    mais, e nada no banco reclamaria.
    """
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "UPDATE solicitation SET form_id = NULL WHERE form_id IN "
            "(SELECT id FROM solicitation_form WHERE slug = :s)"
        ),
        {"s": SLUG_DO_FORMULARIO},
    )
    conn.execute(
        sa.text("DELETE FROM solicitation_form WHERE slug = :s"),
        {"s": SLUG_DO_FORMULARIO},
    )
